package com.selenium2.easy.test.server.xml;

import javax.xml.bind.annotation.XmlEnum;

@XmlEnum
public enum OperationType {
	CLEAR_VALUE, CLICK_ACTION, FIND_ONE, FIND_MANY, FIND_WITHIN, GET_ATTRIBUTE, GET_CSS, GET_LOCATION,
	GET_PAGE_SOURCE, GET_PAGE_TITLE, GET_RECT, GET_SIZE, GET_TAG, IS_DISPLAYED, IS_ENABLED, IS_SELECTED,
	SET_VALUE, SUBMIT_ACTION, TAKE_SCREENSHOT_FROM
}
