package selenium2_easy_test_plugin;

import java.io.File;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import selenium2_easy_test_plugin.config.Selenium2ServerConfig;
import selenium2_easy_test_plugin.config.Selenium2ServerEntry;

import com.selenium2.easy.test.server.automated.SeleniumAutomatedServer;
import com.selenium2.easy.test.server.exceptions.FrameworkException;
import com.selenium2.easy.test.server.exceptions.NotFoundException;

/**
 * Selenium2 Automated Test Framework Mojo Plug-in JUnit Integration Tests
 * <br/>'Execution' Goal which connect a Selenium2 Automated Test Server.
 * <br/>
 * <br/>Here we check the availability of the main configuration paths:
 * <br/>
 * <ul>
 * <br/><li><b>Property file configuration</b> This feature allows to load a property file with the configuration of the Test Suite</li>
 * <br/><li><b>Classes List dynamic configuration</b> This feature creates a configuration file and a test engine using the class list loading (concurrent with the next two configurations)</li>
 * <br/><li><b>Package dynamic configuration</b> This feature creates a configuration file and a test engine using the package classes loading (concurrent with the previous and next configurations)</li>
 * <br/><li><b>XML files directory dynamic configuration</b> This feature creates a configuration file and a test engine using the XML file test cases saved inside a directory (concurrent with the previous two configurations)</li>
 * </ul>
 * <br/>
 * @see Selenium2ServerConfig
 * @see Selenium2ServerEntry
 * @see SeleniumAutomatedServer
 * @author Fabrizio Torelli
 */
@Mojo(defaultPhase=LifecyclePhase.TEST, threadSafe=true, name="execute")
public class ExecuteSeleniumServerPlugin extends AbstractMojo {
	
	@Parameter(defaultValue = "target/selenium2", readonly = false )
	private String temporaryPath = "target/selenium2";


	/**
	 * List of Selenium2 Test Suite configuration properties file to be loaded in a relative list of
	 * Selenium2 Automated Test Framework Engine.
	 */
	@Parameter(required=false )
	private List<String> configFiles;

	/**
	 * List of Selenium2 Configuration Properties used to create a relative list of Test Suite configuration properties files 
	 * to have loaded in a relative list of Selenium2 Automated Test Framework Engine.
	 */
	@Parameter(required=false )
	private Selenium2ServerConfig settings;

	private List<SeleniumAutomatedServer> servers = null;

	/**
	 * Default Plug-in constructor
	 */
	public ExecuteSeleniumServerPlugin() {
	}

	/*
	 * Clean a folder and all content files or delete a file in recursive way.
	 */
	private synchronized void cleanFolderOrFile(File file) {
		file.setReadable(true);
		file.setWritable(true);
		if (file.isDirectory()) {
			for(File child: file.listFiles()) {
				cleanFolderOrFile(child);
			}
		}
		else {
			file.delete();
		}
	}
	
	/*
	 * Create a temporary directory path and if it exists clean it before exit.
	 */
	protected synchronized void cleanTemporaryPath(String outDirectoryPath) {
		File directory = new File(outDirectoryPath);
		if (!directory.exists()) {
			directory.mkdirs();
		}
		else if (!directory.isDirectory()) {
			directory.setReadable(true);
			directory.setWritable(true);
			directory.delete();
			directory.mkdirs();
			directory.setReadable(true);
			directory.setWritable(true);
		}
		else {
			for(File file: directory.listFiles()) {
				this.cleanFolderOrFile(file);
				
			}
		}
		
	}

	/*
	 * Create and save in a directory a new Selenium2 Test Suite configuration properties file
	 * according to the passed {@link Selenium2ServerEntry}.
	 */
	protected synchronized File initFile(Selenium2ServerEntry entry, String outDirectoryPath) {
		String randomCode = UUID.randomUUID().toString().replace('-', '_');
		File directory = new File(outDirectoryPath);
		if (directory.isDirectory()) {
			String propertiesFile = null;
			PrintStream fileWriteStream = null;
			try {
				propertiesFile = directory.getAbsolutePath() + File.separator
						+ randomCode + ".properties";
				fileWriteStream = new PrintStream(propertiesFile);
				entry.getMergedProperties()
						.store(fileWriteStream,
								"..::°° Generated by the Selenium2 Automated Test Server Plugin °°::..");
				return new File(propertiesFile);
			} catch (Throwable e) {
				getLog().warn("Server Configurations File save failed for Selenium2 Automated Server Plugin on file  : " + propertiesFile + " caused by :", e);
			}
			finally {
				if (fileWriteStream!=null) {
					try {
						fileWriteStream.close();
					} catch (Throwable e2) {
						getLog().warn("Server Configurations File close stream failed for Selenium2 Automated Server Plugin on file : " + propertiesFile + " caused by :", e2);
					}
				}
			}
		}
		return null;
	}

	/*
	 * Create The List of {@link SeleniumAutomatedServer} to have used in the multiple Test Suite
	 * execution according to the plug-in configuration. 
	 */
	protected List<SeleniumAutomatedServer> initPlugin() {
		List<SeleniumAutomatedServer> servers = new ArrayList<SeleniumAutomatedServer>(0);
		if ((settings!=null && settings.size()>0) || (configFiles!=null && configFiles.size()>0)) {
			if ((configFiles!=null && configFiles.size()>0)) {
				for(String initFilePath:configFiles) {
					File initFile = new File(initFilePath);
					if (initFile!=null && initFile.exists() && initFile.isFile()) {
						try {
							SeleniumAutomatedServer testServer = new SeleniumAutomatedServer();
							testServer.readConfig(initFile);
							servers.add(testServer);
						} catch (NotFoundException e) {
							getLog().warn("Server Configurations File load failed for Selenium2 Automated Server Plugin on file  : " + initFilePath + " caused by :", e);
						} catch (FrameworkException e) {
							getLog().warn("Server Configurations File load failed for Selenium2 Automated Server Plugin on file  : " + initFilePath + " caused by :", e);
						} catch (Throwable e) {
							getLog().warn("Server Configurations File load failed for Selenium2 Automated Server Plugin on file  : " + initFilePath + " caused by :", e);
						}
					}
					else {
						getLog().warn("Server Configurations File not valid for Selenium2 Automated Server Plugin on file  : " + initFilePath);
					}
				}
			}
			if ((settings!=null && settings.size()>0)) {
				if (!new File(temporaryPath).exists()) {
					new File(temporaryPath).mkdir();
				}
				for(Selenium2ServerEntry initEntry:settings.getSuites()) {
						try {
							File initFile = this.initFile(initEntry, temporaryPath);
							if (initFile!=null && initFile.exists() && initFile.isFile()) {
								SeleniumAutomatedServer testServer = new SeleniumAutomatedServer();
								testServer.readConfig(initFile);
								servers.add(testServer);
							}
							else {
								getLog().warn("Server Configurations File not valid for Selenium2 Automated Server Plugin on file  : " + (initFile !=null ? initFile.getAbsolutePath():null));
							}
						} catch (NotFoundException e) {
							getLog().warn("Server Configurations File load failed for Selenium2 Automated Server Plugin on file  : " + initEntry + " (to should write to the directory:"+temporaryPath+") caused by :", e);
						} catch (FrameworkException e) {
							getLog().warn("Server Configurations File load failed for Selenium2 Automated Server Plugin on file  : " + initEntry + " (to should write to the directory:"+temporaryPath+") caused by :", e);
						} catch (Throwable e) {
							getLog().warn("Server Configurations File load failed for Selenium2 Automated Server Plugin on file  : " + initEntry + " (to should write to the directory:"+temporaryPath+") caused by :", e);
						}
				}
			}
		}
		else {
			getLog().error("No Server Configurations found for Selenium2 Automated Server Plugin");
		}
		return servers;
	}
	/* (non-Javadoc)
	 * @see org.apache.maven.plugin.Mojo#execute()
	 */
	public void execute() throws MojoExecutionException, MojoFailureException {
		getLog().info("Selenium2 Automated Server Maven running ....");
		servers = initPlugin();
		if (servers.size()>0) {
			for(SeleniumAutomatedServer server: servers) {
				try {
					if (server != null) {
						server.startTests();
					}
					else {
						getLog().error("Unable to start the Selenium2 Automated Server!!");
					}
				} catch (Exception e) {
					getLog().error("Error during the STARTUP of the Selenium2 Automated Server caused by :");
					getLog().error(e);
				}
			}
		}
		else {
			getLog().error("No Server Configurations found for the Selenium2 Automated Server Plugin : check the configuration");
		}
		getLog().info("Selenium2 Automated Server Maven exit ....");
	}

	/**
	 * Retrieves the temporary path to save the plug-in generated files
	 * @return The temporary path string
	 */
	public String getTemporaryPath() {
		return temporaryPath;
	}

	/**
	 * Sets the temporary path to save the plug-in generated files
	 * @param temporaryPath The temporary path string
	 */
	public void setTemporaryPath(String temporaryPath) {
		this.temporaryPath = temporaryPath;
	}

	/**
	 * Retrieves the list of Test Suite configuration properties file path strings 
	 * @return The list of configuration files
	 */
	public List<String> getConfigFiles() {
		return configFiles;
	}

	/**
	 * Sets the list of Test Suite configuration properties file path strings 
	 * @param configFiles The list of configuration files
	 */
	public void setConfigFiles(List<String> configFiles) {
		this.configFiles = configFiles;
	}

	/**
	 * Retrieves the {@link Selenium2ServerConfig} that is the dynamic Test Suite configurations container
	 * @return The {@link Selenium2ServerConfig}
	 */
	public Selenium2ServerConfig getSettings() {
		return settings;
	}

	/**
	 * Sets the {@link Selenium2ServerConfig} that is the dynamic Test Suite configurations container
	 * @param configurations The {@link Selenium2ServerConfig}
	 */
	public void setSettings(Selenium2ServerConfig configurations) {
		this.settings = configurations;
	}
}
